apiVersion: apps/v1
kind: Deployment
metadata:
  # The namespace of the application
  name: weather-app
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: weather-app
  
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      
      containers:
      - name: weather-app
        image: rebachi/eks:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: ClusterIP
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: your-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-app-service
                port:
                  number: 80
